# Generated by Django 4.1 on 2023-11-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(db_column='seq')),
                ('chart', models.CharField(db_column='chart', max_length=13)),
                ('C_Date', models.DateTimeField(db_column='C_Date')),
                ('C_Type', models.IntegerField(db_column='C_Type')),
                ('C_SubType', models.IntegerField(db_column='C_SubType')),
                ('F_Type', models.IntegerField(db_column='F_Type')),
                ('Image_Pos', models.IntegerField(db_column='Image_Pos')),
                ('Tooth_Pos', models.IntegerField(db_column='Tooth_Pos')),
                ('Pano_Modality', models.IntegerField(db_column='Pano_Modality')),
                ('Ceph_Modality', models.IntegerField(db_column='Ceph_Modality')),
                ('Standard_Modality', models.IntegerField(db_column='Standard_Modality')),
                ('Camera_Modality', models.IntegerField(db_column='Camera_Modality')),
                ('CT_Modality', models.IntegerField(db_column='CT_Modality')),
                ('Pacs_Modality', models.IntegerField(db_column='Pacs_Modality')),
                ('PacsSModality', models.CharField(db_column='Pacs_SModality', max_length=32)),
                ('Comment', models.CharField(db_column='Comment', max_length=256)),
                ('CIPName', models.CharField(db_column='C_IPName', max_length=15)),
                ('I_TreatCode', models.IntegerField(db_column='I_TreatCode')),
                ('ISubTreatCode', models.CharField(db_column='I_SubTreatCode', max_length=64)),
            ],
            options={
                'db_table': 'imginfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SogeView',
            fields=[
                ('chart', models.CharField(db_column='Chart', max_length=13, primary_key=True, serialize=False)),
                ('Name', models.CharField(db_column='Name', max_length=100)),
                ('first_day', models.DateTimeField(db_column='first_day')),
                ('Last_Day', models.DateTimeField(db_column='Last_Day')),
                ('Office', models.CharField(db_column='Office', max_length=15)),
                ('referkind', models.CharField(db_column='referkind', max_length=1)),
                ('h_zip', models.CharField(db_column='h_zip', max_length=6)),
                ('h_juso2', models.CharField(db_column='h_juso2', max_length=100)),
                ('c_phone', models.CharField(db_column='c_phone', max_length=15)),
                ('h_phone', models.CharField(db_column='h_phone', max_length=15)),
                ('o_Phone', models.CharField(db_column='o_Phone', max_length=15)),
                ('chamgo', models.CharField(db_column='chamgo', max_length=100)),
                ('refer', models.CharField(db_column='refer', max_length=11)),
                ('referchart', models.CharField(db_column='referchart', max_length=20)),
                ('piboname', models.CharField(db_column='piboname', max_length=16)),
                ('jumin', models.CharField(db_column='jumin', max_length=13)),
                ('jongbeul', models.CharField(db_column='jongbeul', max_length=1)),
                ('k_number', models.CharField(db_column='k_number', max_length=15)),
                ('Kiho', models.CharField(db_column='Kiho', max_length=10)),
                ('kwan', models.CharField(db_column='kwan', max_length=1)),
                ('team', models.CharField(db_column='team', max_length=2)),
                ('chart2', models.CharField(db_column='chart2', max_length=13)),
            ],
            options={
                'db_table': 'SogeView',
                'managed': False,
            },
        ),
    ]
