# Generated by Django 4.1 on 2023-12-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apdental', '0002_tbpatientinfo_tbreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbResveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_datetime', models.CharField(db_column='begin_datetime ', max_length=17)),
                ('font_color', models.CharField(db_column='font_color', max_length=3)),
                ('back_color', models.CharField(db_column='back_color', max_length=9)),
                ('pnt_name', models.CharField(db_column='pnt_name', max_length=4)),
                ('resi_no', models.CharField(db_column='resi_no', max_length=7)),
            ],
            options={
                'db_table': 'TB_RESVE_INFO',
                'managed': False,
            },
        ),
    ]
